### ISSUE TITLE
Discussion: App distribution?

### ISSUE THREAD

**Issue by acheronfail** [acheronfail/pixel-picker#18]
It's been requested a few times now, to have PixelPicker available in the Mac AppStore so that it's more easily accessible.

The original intention was to create a pixel-picking app that was completely free to use, since this functionality is something that I believe should be part of any OS.

I have received on multiple occasions however, requests to place it on the Mac AppStore.

In any case, I _might_ put it up on the Mac AppStore, on the condition that it's still freely available here. A similar concept to how [GrandPerspective](http://grandperspectiv.sourceforge.net/) is developed and released.

---

Actions

* [x] Create a Homebrew Cask for PixelPicker
* [ ] (Maybe?) Publish it to the Mac AppStore

**Comment by acheronfail** [comment]
Actually, _technically we probably won't be able_ to submit this to the Mac AppStore, since it uses some private APIs for some required functionality...

I'll look into re-writing some of the code to see if a workaround can be produced.

**Comment by JeffersonBe** [comment]
Also thinking for non MAS, you could distribute your app using Cask.

[https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md)

**Comment by acheronfail** [comment]
That's actually a good idea. I'll look into creating a Homebrew Cask for it.
Might have to wait until I renew my Apple Developer Membership so I can codesign the binary though.

**Comment by acheronfail** [comment]
https://github.com/Homebrew/homebrew-cask/pull/59124

**Comment by JeffersonBe** [comment]
🙌🏾 Thanks!

**Comment by acheronfail** [comment]
Closing this since `homebrew` is enough for now.
