### ISSUE TITLE
Mouse pointer frozen over menu bar icon

### ISSUE THREAD

**Issue by brumm** [acheronfail/pixel-picker#21]
Just had a bug where after right-clicking the menubar icon and dismissing the picker (I think thats what I did), my mouse pointer was frozen at the menubar point and I could not move it away.
Clicking still worked however, and triggered the menu bar icon menu. I did manage to kill `Pixel Picker.app` via Terminal, after which I could move the mouse pointer again.
Unfortunately I can't seem to reproduce it, but I thought I'd report it nevertheless.

Thanks for making a good, free color picker!

**Comment by acheronfail** [comment]
I'm going to close this, feel free to re-open if it happens again!
