### ISSUE TITLE
Support moving the picker with arrow keys

### ISSUE THREAD

**Issue by brumm** [acheronfail/pixel-picker#23]
Hey,

I quite often find myself trying to move the picker by 1 pixel increments by hitting the arrow keys. This happens especially when trying to pick very specific pixels, and even when I'm using focus mode.
(I could also imagine that this would help people with reduced motor control, who would have trouble perfectly locating a specific pixel.)

Currently, Left/Right Arrow cycle though the available color formats. I'd like to start a conversation around changing this behavior and allowing to move the picker window with the arrow keys. Maybe Shift+Arrow could move by 10 pixels?

**Comment by acheronfail** [comment]
This is a great idea! 👍 

Unfortunately, I no longer have a machine running macOS, but I'd be more than happy to accept Pull Requests for this feature. 😄

**Comment by adrianniebla** [comment]
The left and right arrow keys are being used, would vim style keys work (H, J, K, and L)?

**Comment by acheronfail** [comment]
Without a doubt they would. 👍
