### ISSUE TITLE
Incorrect CSS HSL values: shows HSB instead of HSL

### ISSUE THREAD

**Issue by pratyushmittal** [acheronfail/pixel-picker#27]
Hey, this is a wonderful menubar tool.

I tried to use it for picking colours for my website. However, the pasted HSL values looked very different from picked colour.

I checked the code to see the reason. It seems we are showing HSB (hue, saturation and brightness) instead of HSL (hue, saturation and lightness). [HSB an HSL are different](https://stackoverflow.com/a/19602529/232649).

https://github.com/acheronfail/pixel-picker/blob/f843510abe7c71d8b13b9af70bdd225794a63d0b/Pixel%20Picker/PPColor.swift#L222-L227

**Steps to reproduce:**

![Screenshot 2020-05-13 at 9 27 36 AM](https://user-images.githubusercontent.com/1546426/81769746-097bd000-94fc-11ea-9d46-1caf3360bf45.png)

HEX Color: #222b9c
HSB value (shown as HSL in Pixel-picker): hsl(235, 78%, 61%)
Correct HSL value: hsl(235, 64%, 37%)

**Comment by acheronfail** [comment]
Good find! Is there an API on `NSColor` that lets use light lightness instead of brightness? I don't believe there is.

Looking around, it seems we could some take inspiration from here: https://github.com/1024jp/WFColorCode/blob/develop/Sources/ColorCode/NSColor%2BHSL.swift
