### ISSUE TITLE
Catalina issues, can't open a context menu

### ISSUE THREAD

**Issue by Stanko** [acheronfail/pixel-picker#29]
Hello,
Thank you making this wonderful color picker, the amount of features is just right.

But I just installed it on macOS Catalina 10.15.5 and I can't open a context menu. Left click does nothing, icon is highlighted for a moment but that is it.

Any ideas?

**Comment by acheronfail** [comment]
I've just had access to a MacBook Pro (2015) that has macOS Catalina 10.15.7 installed.
After various testing I couldn't replicate this issue at all...

Are you still facing the issue? Does it happen consistently?

Does it still happen if you swap the mouse buttons that opens the context menu? You can do this via:

```
defaults write com.acheronfail.pixel-picker leftClickActivates -bool true
```

Let us know if you have the chance to test. :)

**Comment by Stanko** [comment]
Hey, unfortunately I updated to BigSur in the meantime, so I'm not able to test 🙈 and everything works now 🙂
