### ISSUE TITLE
Adjust magnification on-the-fly via keyboard/mouse

### ISSUE THREAD

**Issue by iliyang** [acheronfail/pixel-picker#36]
It would be very convenient to be able to change the magnification level during picking, e.g. using the `[` and `]` keys (which are commonly used in photon manipulation apps for adjusting the brush size), or maybe the `+` and `-` keys, and also the mouse scroll wheel.

This should be an easy change and ideally I should be able to submit a pull request for this, but sadly I have no experience with Swift and native MacOS app development.

Cheers for the great and lightweight app!

**Comment by viktorstrate** [comment]
I'd appreciate if `+` and `-` also was supported as not all keyboards have the `[` and `]` keys directly.
For example the danish/swedish/norwegian keyboards doesn't.

**Comment by iliyang** [comment]
> I'd appreciate if `+` and `-` also was supported as not all keyboards have the `[` and `]` keys directly.

Hopefully both can be used, or maybe configured in the dropdown menu.

**Comment by acheronfail** [comment]
Try out https://github.com/acheronfail/pixel-picker/releases/tag/1.6.0 and let me know how that works for you!

**Comment by iliyang** [comment]
Wow, that was quick, thanks a lot! Both `[` `]` and `-` `+` work as expected!

Minor thing: maybe the zoom window should also expand according to the magnification level, so that the same set of pixels are visible inside the window.
